//pages
export const FETCH_PAGES = 'FETCH_PAGES'

//reservations
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS'
export const EDIT_RESERVATION = 'EDIT_RESERVATION'

//appState
export const EDIT_STATE = 'EDIT_STATE'

// users
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';

//UI
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';